export const dict = {
  de: {
    en: 'Englisch',
    de: 'Deutsch',
    'FREE SHIPPING AND RETURNS': 'KOSTENLOSER VERSAND UND RÜCKSENDUNG',
    Shoes: 'Schuhe',
    Bags: 'Taschen',
    Women: 'Damen',
    Men: 'Herren',
    Sport: 'Sport',
    'No items': '(noch) keine Artikel',
    'Total Amount': 'Gesamtsumme',
    Search: 'Suche',
    Order: 'Bestellen',
    'The 3 Pairs of Shoes You Need for this Winter':
      'Die 3 Paar Schuhe, die du für diesen Winter brauchst',
    'Shop now': 'Jetzt shoppen',
    'Add to Cart': 'In den Warenkorb',
    'JOIN OUR NEWSLETTER!': 'Melde dich für Newsletter an!',
    'Keep up to date': 'Bleib auf dem Laufenden',
    'Your Email': 'Deine Email',
    'I am mostly interested in': 'Mich interessiert am meisten',
    "Women's Fashion": 'Damenmode',
    "Men's Fashion": 'Herrenmode',
    'Add my Email': 'Anmeldung bestätigen',
    'Invalid input': 'Ungültige Eingabe',
    'Email was added': 'Email hinzugefügt',
    'You can unsubscribe at any time free of charge. Just a demo, no emails are stored':
      'Du kannst dich jederzeit kostenlos abmelden. Nur eine Demo, es werden keine Emails gespeichert',
    'Help & Contact': 'Hilfe & Kontakt',
    'When you complete your order, we will show you in what timeframe your package is expected to arrive':
      'Wenn du deine Bestellung abschließt, zeigen wir dir, in welchem Zeitrahmen dein Paket voraussichtlich eintreffen wird',
    'Gift cards': 'Gutscheine',
    'You can redeem your promotional voucher in the last step of the order process. Enter the voucher code in the "Vouchers and discount codes" field.':
      'Du kannst deinen Gutschein im letzten Schritt des Bestellvorgangs einlösen. Gib den Gutscheincode in das Feld "Gutscheine und Rabattcodes" ein.',
    Shipping: 'Lieferung',
    'If you are shipping internationally, there are several delivery speed options available during the checkout process, usually standard, express and priority delivery.':
      'Beim internationalen Versand stehen dir während des Bestellvorgangs mehrere Optionen für die Liefergeschwindigkeit zur Verfügung, in der Regel Standard-, Express- und Priority-Lieferung.',
    About: 'Über uns',
    Imprint: 'Impressum',
    'Terms & Conditions': 'AGB',
    'Data settings': 'Dateneinstellungen',
    'Find more inspiration:': 'Für mehr Inspiration:',
  },
  en: {
    en: 'English',
    de: 'German',
    'FREE SHIPPING AND RETURNS': 'FREE SHIPPING AND RETURNS',
    Shoes: 'Shoes',
    Bags: 'Bags',
    Women: 'Women',
    Men: 'Men',
    Sport: 'Sport',
    'No items': 'No items (yet!)',
    'Total Amount': 'Total Amount',
    Search: 'Search',
    Order: 'Order',
    'The 3 Pairs of Shoes You Need for this Winter':
      'The 3 Pairs of Shoes You Need for this Winter',
    'Shop now': 'Shop now',
    'Add to Cart': 'Add to Cart',
    'JOIN OUR NEWSLETTER!': 'JOIN OUR NEWSLETTER!',
    'Keep up to date': 'Keep up to date',
    'Your Email': 'Your Email',
    'I am mostly interested in': "I'm mostly interested in",
    "Women's Fashion": "Women's Fashion",
    "Men's Fashion": "Men's Fashion",
    'Add my Email': 'Add my Email',
    'Invalid input': 'Invalid input',
    'Email was added': 'Email was added',
    'You can unsubscribe at any time free of charge. Just a demo, no emails are stored':
      'You can unsubscribe at any time free of charge. Just a demo, no emails are stored',
    'Help & Contact': 'Help & Contact',
    'When you complete your order, we will show you in what timeframe your package is expected to arrive':
      'When you complete your order, we will show you in what timeframe your package is expected to arrive',
    'Gift cards': 'Gift cards',
    'You can redeem your promotional voucher in the last step of the order process. Enter the voucher code in the "Vouchers and discount codes" field.':
      'You can redeem your promotional voucher in the last step of the order process. Enter the voucher code in the "Vouchers and discount codes" field.',
    Shipping: 'Shipping',
    'If you are shipping internationally, there are several delivery speed options available during the checkout process, usually standard, express and priority delivery.':
      'If you are shipping internationally, there are several delivery speed options available during the checkout process, usually standard, express and priority delivery.',
    About: 'About',
    Imprint: 'Imprint',
    'Terms & Conditions': 'Terms & Conditions',
    'Data settings': 'Data settings',
    'Find more inspiration:': 'Find more inspiration:',
  },
};
