export { default as InfoBar } from './Header/InfoBar';
export { default as Navbar } from './Header/Navbar';
export { default as NavbarMobile } from './Header/NavbarMobile';
export { default as SearchBar } from './Header/SearchBar';
export { default as Product } from './Products/Product';
export { default as NewsletterForm } from './Newsletter/NewsletterForm';
export { default as FrequentQuestion } from './Faqs/FrequentQuestion';
export { default as Modal } from './Cart/Modal';
export { default as CartModalProduct } from './Cart/CartModalProduct';
